package com.ooprogramming.TicketingSystem.entities;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;

@Entity

public class EventEntity {

//    Autogenerated eventid
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long eventid;

    private String event_name;
    private String event_description;
    private Integer maxTicketCapacity;
    private Integer ticketReleaseRate;
    private Integer customerRetrievalRate;

//    getters for variables

    public Long getEventid() {
        return eventid;
    }

    public String getEvent_name() {
        return event_name;
    }

    public String getEvent_description() {
        return event_description;
    }



    public Integer getMaxTicketCapacity() {
        return maxTicketCapacity;
    }

    public Integer getTicketReleaseRate() {
        return ticketReleaseRate;
    }

    public Integer getCustomerRetrievalRate() {
        return customerRetrievalRate;
    }

//    setters for variables

    public void setEventid(Long eventid) {
        this.eventid = eventid;
    }

    public void setEvent_name(String eventName) {
        this.event_name = eventName;
    }

    public void setEvent_description(String eventDescription) {
        this.event_description = eventDescription;
    }



    public void setMaxTicketCapacity(Integer maxTicketCapacity) {
        this.maxTicketCapacity = maxTicketCapacity;
    }

    public void setTicketReleaseRate(Integer ticketReleaseRate) {
        this.ticketReleaseRate = ticketReleaseRate;
    }

    public void setCustomerRetrievalRate(Integer customerRetrievalRate) {
        this.customerRetrievalRate = customerRetrievalRate;
    }
}
